-- AlterTable
ALTER TABLE `quiz_sessions` ADD COLUMN `currentQuestionIndex` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `questionStartTime` DATETIME(3) NULL,
    MODIFY `status` ENUM('PENDING', 'ACTIVE', 'WAITING_NEXT_QUESTION', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'PENDING';
